opt_in_rules:
    # 강제 언래핑은 피해야합니다. https://realm.github.io/SwiftLint/force_unwrapping.html
    - force_unwrapping
    
excluded: # SwiftLint 검사에서 제외할 파일 경로
  - Pods
  - Diary/AppDelegate.swift
  - Diary/SceneDelegate.swift
  
#- 네이밍 규칙 -#

### min_length 및 max_length에 대한 warning/error를 설정할 수 있습니다.
### 규칙에 제외되는 특수한 이름도 지정할 수 있습니다.
type_name:
  min_length: 4 # only warning
  max_length: # warning and error
    warning: 40
    error: 50
  excluded: iPhone # excluded via string
  allowed_symbols: ["_"] # these are allowed in type names

identifier_name:
  min_length: 4 # only min_length
  excluded: # excluded via string array
    - id
    - URL
    - GlobalAPIKey


    
