excluded:
  - Pods
force_cast: error
force_try:
    severity: error
line_length:
    warning: 110
    error: 120
disabled_rules:
    - vertical_whitespace
    - trailing_whitespace
    - unused_optional_binding
    - notification_center_detachment
    - todo
    - unused_capture_list
    - unused_closure_parameter
