#<?xml version="1.0" encoding="UTF-8" standalone="no"?>
#<document type="com.apple.InterfaceBuilder3.CocoaTouch.XIB" version="3.0" toolsVersion="13142" targetRuntime="iOS.CocoaTouch" propertyAccessControl="none" useAutolayout="YES" useTraitCollections="YES" useSafeAreas="YES" colorMatched="YES">
#    <dependencies>
#        <plugIn identifier="com.apple.InterfaceBuilder.IBCocoaTouchPlugin" version="12042"/>
#    </dependencies>
#    <objects>
#        <placeholder placeholderIdentifier="IBFilesOwner" id="-1" userLabel="File's Owner"/>
#        <placeholder placeholderIdentifier="IBFirstResponder" id="-2" customClass="UIResponder"/>
#    </objects>
#</document>


disabled_rules: # Default Rules에서 비활성화할 규칙
    
    # 라인 뒤에 공백이 없어야 합니다. https://realm.github.io/SwiftLint/trailing_whitespace.html
    - trailing_whitespace
    
    # 강제 캐스팅은 피해야합니다. https://realm.github.io/SwiftLint/force_cast.html
    - force_cast
    
    # 강제 언래핑은 피해야합니다. https://realm.github.io/SwiftLint/force_unwrapping.html
    - force_unwrapping
    
    - line_length
    - closure_parameter_position
    - unused_closure_parameter
